project:
  type: website
  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "assets/**/**"
    
execute:
  freeze: auto

# metadata  
pagetitle: "Gonzalo Garcia-Castro"
author-meta: "Gonzalo Garcia-Castro"

# bibliography settings
bibliography: assets/bib/references.bib
csl: assets/bib/apa7.csl

website:
  title: "Gonzalo García-Castro"
  description: "Language, stats, R"
  image: "/assets/media/wallpaper.jpg"
  favicon: "/assets/media/favicon.ico"
  repo-url: https://github.com/gongcastro/gongcastro.github.io
  repo-actions: [edit, issue]

  open-graph:
    title: "Gonzalo Garcia-Castro"
    description: "Language, stats, R"
    image: "/assets/media/favicon.jpeg"

  twitter-card: 
    title: "Gonzalo Garcia-Castro"
    card-style: summary
    description: "Language, stats, R"
    creator: "@gongcastro"
    site: "@cbcUPF"
    image: "assets/media/favicon.jpeg"
    
  navbar:
    pinned: true
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV   
      - href: blog.qmd
        text: Blog
    right: 
      - icon: github
        href: https://github.com/gongcastro
        aria-label: GitHub
    search: false
    
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Gonzalo Garcia-Castro</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)</span>      
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>
format:
  html:
    anchor-sections: true
    theme: assets/css/minty-modified.scss
    css:  assets/css/styles.css
    toc: true
    citations-hover: true
    code-link: true
    code-block-bg: "#f7f7f9"
    highlight-style: ayu
    code-fold: show
    html-math-method: mathjax
    linestretch: 1.25
    code-block-border-left: "#31BAE9"
    footnotes-hover: true
    reference-location: margin
    


