theme: "hugo-theme-hello-friend-ng"
baseURL: "http://gongcastro.github.io/"
url-pretty: "gongcastro.gongcastro.io"
languageCode: en-us
title: "Gonzalo García-Castro"

PygmentsCodeFences: yes
PygmentsStyle: monokai
enableRobotsTXT: yes
enableGitInfo: true
enableEmoji: yes
enableSharingButtons: true

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
  
permalinks:
  post: /:year/:month/:day/:slug/
  
menu:
  main:
    - identifier: posts
      name: Posts
      url: post/
      weight: 1
    - identifier: cv
      name: CV
      url: cv/
      weight: 2
    - identifier: about
      name: About
      url: about/
      weight: 3

params:
  customCSS: ["/css/custom.css"]
  social:
    - name: twitter
      url: https://twitter.com/gongcastro
    - name: googlescholar
      url: https://scholar.google.com/citations?user=fHetiuQAAAAJ
    - name: orcid
      url: https://orcid.org/0000-0002-8553-4209
    - name: researchgate
      url: https://www.researchgate.net/profile/Gonzalo-Garcia-Castro
    - name: email
      url: mailto:gonzalo.garciadecastro@upf.edu
    - name: github
      url: https://github.com/gongcastro
    - name: gitlab
      url: https://gitlab.com/gongcastro
    - name: linkedin
      url: https://linkedin.com/in/gongcastro
    - name: docker
      url: https://hub.docker.com/u/gongcastro
    - name: stackoverflow
      url: https://stackoverflow.com/users/14847054/gonzalo-garc%c3%ada-castro
    - name: twitch
      url: https://www.twitch.tv/gongcastro
  themeColor: "#fcba03"
  highlightjsVersion: "11.3.1"
  highlightjsLang: ["r", "yaml", "julia", "bash", "python"]
  highlightjsTheme: "github"
  highlightStyle: "default"
  MathJaxCDN: "//cdn.bootcss.com"
  logo:
    logoHomeLink:
    logoText: $ cd /gongcastro/
    logoCursorColor: "lightsalmon"
  portrait:
    path: "/img/logo.jpg"
    alt: Logo
    maxWidth: 150px

languages:
  en:
    copyright: <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>
    subtitle: "Developmental sycholinguistics and R"
    weight: 1
  es:
    copyright: <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>
    subtitle: "Psicolingüística evolutiva y R"
    weight: 2
