---
title: "CV"
---
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

[Download PDF](https://raw.githubusercontent.com/gongcastro/cv/refs/heads/main/cv.pdf?raw=true)

## Education

October 2018 - Present

> **PhD, Biomedicine**; Universitat Pompeu Fabra (Barcelona, Spain); Supervisor: Núria Sebastian-Galles.

October 2017 - July 2018

> **MSc, Neurosciences**; University of Barcelona (Barcelona, Spain). Dissertation: Phonemic Contrast Perception: A Segmentation Study on Monolingual and Bilingual Infants; Supervisors: Núria Sebastian-Galles and Chiara Santolin.

September 2013 - July 2017

> **BSc, Psychology**; University of Oviedo (Oviedo, Spain). Dissertation: Effects of Environmental Enrichment on Attention, Spatial Reference Memory, and Cytochrome C Oxidase Activity; Supervisors: Azucena Begega and Marcelino Cuesta.

___

## Contributions

### Articles

Santolin, C., **García-Castro, G.**, Zettersten, M., Sebastian-Galles, N., Saffran, J. (2020). Experience with research paradigms relates to infants' direction of preference. Infancy, 00, 1–8.  <a href="https://onlinelibrary.wiley.com/doi/10.1111/infa.12372"><i class="fa fa-link"> URL</i></a> <a href="https://osf.io/g95ub/"><i class="ai ai-osf"></i> OSF</a> <a href="https://psyarxiv.com/xgvbh/"><i class="ai ai-psyarxiv"></i> PsyArxiv</a> <a href="https://doi.org/10.1111/infa.12372"><i class="ai ai-doi"> </i> DOI</a> <a href="https://github.com/gongcastro/Flip"><i class="fa-brands fa-github"></i> GitHub</a>

Sampedro-Piquero, P., Álvarez-Suárez, P., Moreno-Fernández, R., **García-Castro, G.**, Cuesta, M., Begega, A. (2018). Environmental enrichment results in both brain connectivity efficiency and selective improvement in different behavioral tasks. Neuroscience, 388, 374-383. <a href="https://www.sciencedirect.com/science/article/abs/pii/S0306452218305116"><i class="fa fa-link"> URL</i></a> <a href="https://doi.org/10.1016/j.neuroscience.2018.07.036"><i class="ai ai-doi"> </i> Google Scholar</a>

## Conference presentations

Siow, S., Guillen, N., Lepadatu, I., **Garcia-Castro, G.**, Avila-Varela, D., Sebastian-Galles, N., Plunkett, K. (2022). A longitudinal exploration of bilingual toddler's processing of cognates. Presented at the *International Congress on Infant Studies*. <a href="https://infantstudies.org/wp-content/uploads/2022/07/ICIS-2022-Abstract-ProceedingsJuly07.pdf"><i class="fa fa-link"> URL</i></a>

**Garcia-Castro, G.**, Franco-Martínez, A., Rodríguez-Prada, C., Castillejo, I., Sebastian-Galles, N. (2022). Estimando curvas de adquisición léxica en la infancia mediante un modelo de bayesiano de TRI. Presented at the *XVII Congreso de Metodología de las Ciencias Sociales y de la Salud*. <a href="https://eventos.unizar.es/file_manager/getFile/118143.html"><i class="fa fa-link"> URL</i></a>

## Proceedings

Siow, S., Guillen, N., Lepadatu, I., **Garcia-Castro, G.**, Avila-Varela, D., Sebastian-Galles, N., Plunkett, K. (2022). An alternative approach to defining cross-linguistic phonological similarity using a model of monolingual speech recognition. *Proceedings of the 46th annual Boston University Conference on Language Development*. <a href="http://www.lingref.com/bucld/46/BUCLD46-56.pdf"><i class="fa fa-link"> URL</i></a> <a href="https://scholar.google.com/citations?view_op=view_citation&hl=fr&user=fHetiuQAAAAJ&citation_for_view=fHetiuQAAAAJ:UeHWp8X0CEIC"><i class="ai ai-google-scholar"> </i> DOI</a>

Siow, S., Guillen, N., Lepadatu, I., **Garcia-Castro, G.**, Avila-Varela, D., Sebastian-Galles, N., Plunkett, K. (2021). A study of linguistic distance and infant vocabulary trajectories using bilingual CDIs of English and one additional language. Presented at the *Boston University Conference in Language Development*, held online (Boston, United States).


Siow, S., **Garcia-Castro, G.**, Sebastian-Galles, N., Plunkett, K. (2021). An alternative approach to defining cross-linguistic phonological similarity using a model of monolingual speech recognition. Presentation at the *Architectures and Mechanisms for Language Processing* conference, held online (Paris, France). <a href="https://amlap2021.github.io/program/23.pdf"><i class="fa fa-link"> URL</i></a> <a href="https://scholar.google.com/citations?view_op=view_citation&hl=en&user=fHetiuQAAAAJ&citation_for_view=fHetiuQAAAAJ:2osOgNQ5qMEC"><i class="ai ai-google-scholar"> </i> DOI</a>


### Posters

**Garcia-Castro, G.**, Siow, S., Lepadatu, I., Guillen, N., Avila-Varela, D. S., Sebastian-Galles, N., Plunkett, K. (August, 2021). The emergence of inhibitory links in the developing lexicon: insights from bilingual participants. Poster presented at the *Workshop in Infant Language Development* (San Sebastián/Donostia, Spain). <a href="https://www.bcbl.eu/events/files/galeria/files/wild/Bookofabstracts.pdf"><i class="fa fa-link"> URL</i></a>

Zacharaki, K. E., **Garcia-Castro, G.**, Sebastian-Galles, N. (June, 2022). Selective attention to the mouth of signing faces. Poster presented at the *Workshop in Infant Language Development* (San Sebastián/Donostia, Spain). <a href="https://www.bcbl.eu/events/files/galeria/files/wild/Bookofabstracts.pdf"><i class="fa fa-link"> URL</i></a>

Zacharaki, K. E., **Garcia-Castro, G.**, Sebastian-Galles, N. (June, 2022). Selective attention to the mouth of signing faces. Poster presented at the *Workshop in Infant Language Development* (San Sebastián/Donostia, Spain). <a href="https://www.bcbl.eu/events/files/galeria/files/wild/Bookofabstracts.pdf"><i class="fa fa-link"> URL</i></a>


Siow, S., Guillen, N., Lepadatu, I., **Garcia-Castro, G.**, Avila-Varela, D. S., Sebastian-Galles, N., Plunkett, K. (August, 2021). A study of linguistic distance and infant vocabulary trajectories using bilingual CDIs of English and one additional language. Presentation at the *Lancaster Conference on Infant and Early Child Development*, held online (Lancaster, United Kingdom).

**Garcia-Castro, G.**, Siow, S., Sebastian-Galles, N., Plunkett, K. (August, 2021). The impact of cognateness on bilingual lexical access: a longitudinal priming study. Poster presented at the *Lancaster Conference on Infant and Early Child Development*, held online (Lancaster, United Kingdom).


**Garcia-Castro, G.**, Siow, S., Sebastian-Galles, N. and Plunkett, Kim (June, 2021). The role of cognateness in nonnative spoken word recognition. Poster presented at the *XI International Symposium of Psycholinguistics* (Madrid, Spain, held online).

**Garcia-Castro, G.**, Siow, S., Sebastian-Galles, N. and Plunkett, Kim (July, 2020). The role of lexical similarity on bilingual parallel activation: A priming study in toddlers. Poster presented at the *International Congress on Infant Studies* (Edimburgh, United Kingdom, held online). proceedings

**Garcia-Castro, G.**, Avila-Varela, D. S., and Sebastian-Galles, N. (July, 2020). Does phonological overlap across translation equivalents predict earlier age of acquisition?. Poster presented at the *International Congress on Infant Studies* (Edimburgh, United Kingdom, held online). proceedings

Siow, S., **Garcia-Castro, G.**, Sebastian-Galles, N., and Plunkett, K. (August, 2019). The impact of phonology (cognateness) on the bilingual lexicon: Parallel cross-language phonological priming. Poster presented at the *Lancaster Conference on Infant and Early Child Development* (Lancaster, United Kingdom).

**Garcia-Castro, G.**, Marimon, M., Santolin, C., and Sebastian-Galles, N. (June, 2019). Encoding new word forms when contrastive phonemes are interchanged: A preliminary study on 8-month-old infants. Poster presented at the *Workshop in Infant Language Development* (Potsdam, Germany). https://doi.org/10.17605/OSF.IO/GYKUH

**García-Castro, G.**, Álvarez-Suárez, P., García-Abad, N., Cuesta, M., and Begega, A. (June, 2017). Pro-cognitive effects of environmental enrichment on attention and spatial memory: hippocampal metabolic activity in a Wistar rat model. Poster presented at the *4th International Congress on Health and Aging Research* (Murcia, Spain).

García-Abad, N., Santirso, M., **García-Castro, G.**, and Álvarez-Suárez, P. (June, 2017). Efectos del omega-3 en las redes implicadas en la memoria de trabajo espacial en ratas Wistar. Poster presented at the *3rd National Congress of Psychology* (Oviedo, Spain)

### Invited talks

**Garcia-Castro, G.**, Siow, S., Sebastian-Galles, N., and Plunkett, K. (March, 2022). The role of cognateness during word recognition in a non-native language. Talk given at the Psycholinguistics Coffee (University of Edinburgh, held online). <a href="https://blogs.ed.ac.uk/psycholingcoffee/past-meetings/2021-22/"><i class="fa fa-link"> URL</i></a>

**Garcia-Castro, G.**, Siow, S., Lepadatu, I., Guillen, N., Avila-Varela, D., Sebastian-Galles, N. y Plunkett, K. (January 2022). Parallel activation and the developing bilingual lexicon: a longitudinal study on word recognition. Talk given at the LACRE research group (Cardiff University, held online).

### Scientific dissemination

Zacharaki, K., **García-Castro, G.** (2019, October). “Descubriendo la mente de los bebés” Talk presented at 13a Festa de la Ciència, Barcelona, Spain. [Link] [Video]

**García-Castro, G.**, Avila-Varela (2019, October). “Estudiando la mente de los bebés: Desde el lenguaje hasta la lógica” Talk presented at Centre Cívic, Barcelona, Spain. [Link] [Video])

### Repositories

**García-Castro, G.**, Santolin, C., Marimon, M., and Sebastian-Galles, N. (2019, October 22th). Segmentation: Catalan and Spanish natural speech segmentation at 8 months of age. https://doi.org/10.17605/OSF.IO/42GUP)

Santolin, C., **García-Castro, G.**, Zettersten, M., Sebastian-Galles, N., & Saffran, J. (2020, March 5). Flip: Experience with research paradigms relates to infants’ direction of preference. https://doi.org/10.17605/OSF.IO/G95UB

___

## Others

### Animal research

Research Staff Certificate for animal research, issued on 15/05/2018 by the Direcció General de Polítiques Ambientals i Medi Natural.

### Skills

* Data processing: I particularly enjoy wrangling my way through messy data using the `tidyverse` family of packages. with some time, I can also google my way through Python.
* Data analysis: Linear mixed models using R, both frequentist (`lme4`) and Bayesian (`brms`); reproducible reports using `RMarkdown`. I can also perform acoustic analysis on stimuli using Praat, and one of its R interfaces (`PraatR`).
* Data visualisation using `ggplot2`. I can make animations using `gganimate`, and I’m currently learning to make maps, and Shiny Apps.
* Designing experiments and questionnaires: I can program lab-based experiments using Matlab (PsychToolbox-3) and Python (Psychopy), online experiments using the PsychoPy/PsychoJS/Pavlovia workflow, and design reproducible online questionnaires using formR.
* Git/GitHub/Bitbucket
* JASP/SPSS

## Languages

* Spanish (native speaker)
* English: C1
* French: C1

## Short courses

August 2018

> **Data Science: Multiple imputation in practice**, Utrecht Summer School, Utrecht University. Introduction to Multiple Imputation as a powerful tool for dealing with missing data in experimental studies.

August 2018

> **Data Science: Statistical Programming with R**, Utrecht Summer School, Utrecht University.

August 2016

> **Introduction to Neuroscience: From Molecule to Behavior**, Radboud Summer School, Radboud University Nijmegen. Hands-on training at research labs of the Donders Institute for Brain and Cognition.

August 2016

> **How to Improve the Quality and Translatability of Preclinical Animal Studies**, Radboud Summer School, Radboud University Nijmegen. Course organized by SYRCLE institute, Radboud University Nijmegen and Radboud University Medical Centre. Theory and hands-on experience on Systematic Reviews and Meta-Analysis in preclinical animal studies. Overview of the main software available to conduct a Meta-Analysis and basic formation on academic reading and writing.

___

